version: 2

jobs:
  build:
    working_directory: ~/.
    steps:
      - run: apt-get install -y -y cmake make libboost-all-dev libxml2-dev libxml++2.6-dev libsqlite3-dev libhdf5-serial-dev libbz2-dev coinor-libcbc-dev coinor-libcoinutils-dev coinor-libosi-dev coinor-libclp-dev coinor-libcgl-dev libblas-dev liblapack-dev g++ libgoogle-perftools-dev python3-dev python3-tables python3-pandas python3-numpy python3-nose python3-jinja2 cython3 libhdf5-serial-dev gfortran gcc build-essential cmake libblas-dev liblapack-dev git
      - run: apt-get update
      - run: wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
      - run: bash miniconda.sh -b -p $HOME/miniconda
      - run: export PATH="$HOME/miniconda/bin:$PATH"
      - run: conda config --set always_yes yes --set changeps1 no
      - run: conda update -q conda
      # - run: conda install -c conda-forge pyne 
      - run: conda install -c anaconda cython
      - run:
          name: git clone cyclus and cycamore
          command: |
            git clone http://github.com/flanflanagan/cyclus -b time_series
            git clone http://github.com/flanflanagan/cycamore -b d3ploy_update
      - run:
          name: install cyclus and cycamore
          command: |
            python ./cyclus/install.py
            python ./cycamore/install.py
      - run:
          name: install d3ploy
          command: |
            python setup.py install
      - run:
          name: run tests
          command: |
            pytest tests/